// Code generated by Copilot w/ some manual edits.

package vmi_internal

import (
	"bytes"
	"fmt"
	"path"
	"runtime"
	"testing"

	vmi_testutils "github.com/bgp59/victoriametrics-importer/vmi/testutils"
)

type GoInternalMetricsTestCase struct {
	GoVersion                  string
	CurrMemStats, PrevMemStats *runtime.MemStats
	NumGoRoutine               int
	InternalMetricsTestCase
}

var goInternalMetricsTestCasesFile = path.Join(
	VmiTestCasesSubdir,
	"internal_metrics", "go.json",
)

func newTestGoInternalMetrics(tc *GoInternalMetricsTestCase) (*InternalMetrics, error) {
	internalMetrics, err := newTestInternalMetricsTsInit(&tc.InternalMetricsTestCase)
	if err != nil {
		return nil, err
	}
	gim := NewGoInternalMetrics(internalMetrics)
	gim.goVersion = tc.GoVersion
	*gim.memStats[gim.currIndex] = *tc.CurrMemStats
	if tc.PrevMemStats != nil {
		*gim.memStats[1-gim.currIndex] = *tc.PrevMemStats
	}
	gim.numGoRoutine = tc.NumGoRoutine
	internalMetrics.goMetrics = gim
	return internalMetrics, nil
}

func testGoInternalMetrics(tc *GoInternalMetricsTestCase, t *testing.T) {
	tlc := vmi_testutils.NewTestLogCollect(t, RootLogger, nil)
	defer tlc.RestoreLog()

	t.Logf("Description: %s", tc.Description)

	internalMetrics, err := newTestGoInternalMetrics(tc)
	if err != nil {
		t.Fatal(err)
	}

	testMetricsQueue := internalMetrics.MetricsQueue.(*vmi_testutils.TestMetricsQueue)
	buf := testMetricsQueue.GetBuf()

	gim := internalMetrics.goMetrics
	wantCurrIndex := 1 - gim.currIndex

	gotMetricsCount, _, buf := gim.generateMetrics(buf, internalMetrics.TsSuffixBuf.Bytes())
	if buf != nil {
		testMetricsQueue.QueueBuf(buf)
	}

	errBuf := &bytes.Buffer{}

	gotCurrIndex := gim.currIndex
	if wantCurrIndex != gotCurrIndex {
		fmt.Fprintf(
			errBuf,
			"\ncurrIndex: want: %d, got: %d",
			wantCurrIndex, gotCurrIndex,
		)
	}

	wantMetricsCount := len(tc.WantMetrics)
	if wantMetricsCount != gotMetricsCount {
		fmt.Fprintf(
			errBuf,
			"\nmetricsCount: want: %d, got: %d",
			wantMetricsCount, gotMetricsCount,
		)
	}

	testMetricsQueue.GenerateReport(tc.WantMetrics, true, errBuf)

	if errBuf.Len() > 0 {
		t.Fatal(errBuf)
	}
}

func TestGoInternalMetrics(t *testing.T) {
	t.Logf("Loading test cases from %q ...", goInternalMetricsTestCasesFile)
	testCases := make([]*GoInternalMetricsTestCase, 0)
	err := vmi_testutils.LoadJsonFile(goInternalMetricsTestCasesFile, &testCases)
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range testCases {
		batchTargetSizeList := tc.BatchTargetSizeList
		if batchTargetSizeList == nil {
			batchTargetSizeList = []int{0}
		}
		for _, batchTargetSize := range batchTargetSizeList {
			tc.batchTargetSize = batchTargetSize
			t.Run(
				fmt.Sprintf("%s/bsz:%d", tc.Name, tc.batchTargetSize),
				func(t *testing.T) { testGoInternalMetrics(tc, t) },
			)
		}
	}
}
