[tool.autoflake]
exclude = ["**/bin/*", "**/buildinfo/*", "**/local/*", "**/releases/*", "**/runtime/*", "**/staging/*", "**/testdata/*", "**/volumes/*"]
ignore_init_module_imports = true
in_place = true
recursive = true
remove_all_unused_imports = true
remove_unused_variables = true

[tool.isort]
profile = "black"
extend_skip_glob = ["**/bin/*", "**/buildinfo/*", "**/local/*", "**/releases/*", "**/runtime/*", "**/staging/*", "**/testdata/*", "**/volumes/*"]

