#!/bin/bash --noprofile

this_script=${0##*/}
case "$0" in
    /*|*/*) 
        this_dir=$(cd $(dirname $0) && pwd)
    ;;
    *) 
        this_dir=$(cd $(dirname $(which $0)) && pwd)
    ;;
esac

platform="$1"; shift
volumes_dir=volumes${platform:+/}$platform

set -e
cd $this_dir
if [[ ! -d $volumes_dir/runtime ]]; then
    (set -x; mkdir -p $volumes_dir/runtime)
fi
project_root=$(realpath ../../project-root)
volume_project_root=$volumes_dir/$(basename $project_root)
if [[ "$(readlink $volume_project_root)" != "$project_root" ]]; then
    (set -x; ln -fs $project_root $volume_project_root)
fi
