{
 "title": "refvmi-ref",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "vmi_inst", "label": "VMI Inst", "query": { "query": "vmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "vmi_uptime_sec{vmi_inst=~\"${vmi_inst}\"}"
    }
   },
   { "name": "gauge_interval", "query": "1s" },
   { "name": "counter_interval", "query": "500ms" },
   { "name": "categorical_interval", "query": "4s" },
   { "name": "categorical_lookback", "query": "1m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "* See [Metrics](https://github.com/bgp59/victoriametrics-importer/blob/main/reference/README.md#metrics) under VMI [reference](https://github.com/bgp59/victoriametrics-importer/blob/main/reference) code.\n* **IMPORTANT** The `Categorical Timeline` panel requires a specific `VMI Inst` and `Hostname`"
   }
  },
  {
   "title": "Gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "refvmi_gauge{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
     "legendFormat": "{{hostname}}/{{vmi_inst}}"
    }
   ]
  },
  {
   "title": "Counter Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 2 },
   "targets": [
    {
     "expr": "refvmi_counter_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
     "legendFormat": "{{hostname}}/{{vmi_inst}}"
    }
   ]
  },
  {
   "title": "Counter Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "refvmi_counter_rate{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
     "legendFormat": "{{hostname}}/{{vmi_inst}}"
    }
   ]
  },
  {
   "title": "Categorical Timeline For ${vmi_inst}/${hostname}",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(refvmi_categorical{vmi_inst=\"${vmi_inst}\",hostname=\"${hostname}\"}[${categorical_lookback}]) > 0",
     "legendFormat": "{{choice}}"
    }
   ]
  },
  {
   "title": "Latest Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "last_over_time(refvmi_categorical{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}[${categorical_lookback}]) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}