{
 "title": "Internal Metrics (Ref)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "vmi_inst", "label": "VMI Inst", "query": { "query": "vmi_uptime_sec" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "vmi_uptime_sec{vmi_inst=~\"${vmi_inst}\"}"
    }
   },
   {
    "name": "compressor",
    "label": "Compressor ID",
    "query": {
     "query": "vmi_compressor_compression_factor{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "ep_url",
    "label": "EP URL",
    "query": {
     "query": "vmi_http_ep_send_buffer_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}"
    }
   },
   {
    "name": "gen_id",
    "label": "Generator ID",
    "query": {
     "query": "vmi_metrics_gen_invocation_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}"
    }
   },
   { "name": "interval", "query": "5s" },
   { "name": "lookback", "query": "1m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**NOTE**\n\n1. See [VMI Internal Metrics](https://github.com/bgp59/victoriametrics-importer/blob/main/docs/internal_metrics.md) for metrics description.\n"
   }
  },
  {
   "title": "Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agents",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "sum without(__name__) (vmi_uptime_sec)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum without(__name__) (vmi_os_uptime_sec)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum without(__name__) (last_over_time(vmi_os_info[${lookback}]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum without(__name__) (last_over_time(vmi_os_release[${lookback}]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum without(__name__) (last_over_time(vmi_build_info[${lookback}]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Scheduled# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_task_scheduled_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Task Executed# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_task_executed_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Task Average Runtime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "vmi_task_avg_runtime_sec{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Task Delayed# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_task_delayed_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Task Overrun# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_task_overrun_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Task Deadline Hack# Delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_task_next_ts_hack_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Compressors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "vmi_compressor_read_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Read Bytes Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmi_compressor_read_byte_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Compression Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 100 },
     "targets": [
      {
       "expr": "vmi_compressor_compression_factor{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Send# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "vmi_compressor_send_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Send Byte Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmi_compressor_send_byte_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Timeout Flush# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_compressor_tout_flush_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "c{{compressor}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Error# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 108 },
     "targets": [
      {
       "expr": "vmi_compressor_send_error_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "send_err(c{{compressor}}/{{hostname}}/{{vmi_inst}})"
      },
      {
       "expr": "vmi_compressor_write_error_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",compressor=~\"${compressor}\"}",
       "legendFormat": "write_err(c{{compressor}}/{{hostname}}/{{vmi_inst}})"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Send Buffer# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_http_ep_send_buffer_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",url=~\"${ep_url}\"}",
       "legendFormat": "{{hostname}}/{{vmi_inst}}->{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Send Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "vmi_http_ep_send_buffer_byte_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",url=~\"${ep_url}\"} * 8 / on (vmi_inst, hostname) group_left vmi_metrics_gen_dtime_sec{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=\"internal_metrics\"} ",
       "legendFormat": "{{hostname}}/{{vmi_inst}}->{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Error# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_http_ep_send_buffer_error_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",url=~\"${ep_url}\"}",
       "legendFormat": "send_err({{hostname}}/{{vmi_inst}}->{{url}})"
      },
      {
       "expr": "vmi_http_ep_healthcheck_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "healthchk({{hostname}}/{{vmi_inst}}->{{url}})"
      },
      {
       "expr": "vmi_http_ep_healthcheck_error_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",url=~\"${url}\"}",
       "legendFormat": "healthchk_err({{hostname}}/{{vmi_inst}}->{{url}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Generators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Generator Actual Scan Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "vmi_metrics_gen_dtime_sec{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Sample# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 },
     "targets": [
      {
       "expr": "vmi_metrics_gen_metrics_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Sample Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 },
     "targets": [
      {
       "expr": "vmi_metrics_gen_metrics_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}\n/ on(vmi_inst,hostname) group_left\nvmi_metrics_gen_dtime_sec{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=\"internal_metrics\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Invocation# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 158 },
     "targets": [
      {
       "expr": "vmi_metrics_gen_invocation_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Byte# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vmi_metrics_gen_byte_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Metrics Generator Bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "vmi_metrics_gen_byte_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=~\"${gen_id}\"}\n/ on(vmi_inst,hostname) group_left\nvmi_metrics_gen_dtime_sec{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\",gen_id=\"internal_metrics\"}",
       "legendFormat": "{{gen_id}}({{hostname}}/{{vmi_inst}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Go & Process Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vmi_go_mem_sys_bytes{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "sys({{hostname}}/{{vmi_inst}})"
      },
      {
       "expr": "vmi_go_mem_heap_bytes{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "heap({{hostname}}/{{vmi_inst}})"
      },
      {
       "expr": "vmi_go_mem_heap_sys_bytes{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "heap_sys({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "Malloc/Free# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "vmi_go_mem_malloc_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "malloc({{hostname}}/{{vmi_inst}})"
      },
      {
       "expr": "vmi_go_mem_free_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "free({{hostname}}/{{vmi_inst}})"
      }
     ]
    },
    {
     "title": "In Use Object Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "vmi_go_mem_in_use_object_count{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{vmi_inst}}"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_go_num_goroutine{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{vmi_inst}}"
      }
     ]
    },
    {
     "title": "GC# Delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vmi_go_mem_gc_delta{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{vmi_inst}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vmi_proc_pcpu{vmi_inst=~\"${vmi_inst}\",hostname=~\"${hostname}\"}",
       "legendFormat": "{{hostname}}/{{vmi_inst}}"
      }
     ]
    }
   ]
  }
 ]
}